package de.shyim.shopware.ui.theme

import androidx.compose.ui.graphics.Color

// Forest accent — fresh green, M3 tonal
val ForestPrimaryLight = Color(0xFF1E6B3C)
val ForestOnPrimaryLight = Color(0xFFFFFFFF)
val ForestPrimaryContainerLight = Color(0xFFA6F2BF)
val ForestOnPrimaryContainerLight = Color(0xFF00210F)

val ForestPrimaryDark = Color(0xFF8BD6A4)
val ForestOnPrimaryDark = Color(0xFF00391C)
val ForestPrimaryContainerDark = Color(0xFF00522B)
val ForestOnPrimaryContainerDark = Color(0xFFA6F2BF)

val SecondaryLight = Color(0xFF4F6354)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFD2E8D5)
val OnSecondaryContainerLight = Color(0xFF0D1F13)
val TertiaryLight = Color(0xFF3A656F)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFBEEAF6)
val OnTertiaryContainerLight = Color(0xFF001F26)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val SurfaceLight = Color(0xFFF5FBF2)
val OnSurfaceLight = Color(0xFF171D18)
val SurfaceVariantLight = Color(0xFFDDE5DB)
val OnSurfaceVariantLight = Color(0xFF414941)
val OutlineLight = Color(0xFF717971)
val OutlineVariantLight = Color(0xFFC1C9BF)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFEFF5EC)
val SurfaceContainerLight = Color(0xFFE9EFE6)
val SurfaceContainerHighLight = Color(0xFFE3EAE0)
val SurfaceContainerHighestLight = Color(0xFFDDE4DA)
val InverseSurfaceLight = Color(0xFF2C322D)
val InverseOnSurfaceLight = Color(0xFFEDF2EA)

val SecondaryDark = Color(0xFFB6CCBA)
val OnSecondaryDark = Color(0xFF223528)
val SecondaryContainerDark = Color(0xFF384B3D)
val OnSecondaryContainerDark = Color(0xFFD2E8D5)
val TertiaryDark = Color(0xFFA2CEDA)
val OnTertiaryDark = Color(0xFF02363F)
val TertiaryContainerDark = Color(0xFF214D56)
val OnTertiaryContainerDark = Color(0xFFBEEAF6)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val SurfaceDark = Color(0xFF0F1511)
val OnSurfaceDark = Color(0xFFDFE4DC)
val SurfaceVariantDark = Color(0xFF414941)
val OnSurfaceVariantDark = Color(0xFFC1C9BF)
val OutlineDark = Color(0xFF8B938A)
val OutlineVariantDark = Color(0xFF414941)
val SurfaceContainerLowestDark = Color(0xFF0A0F0B)
val SurfaceContainerLowDark = Color(0xFF171D18)
val SurfaceContainerDark = Color(0xFF1B211C)
val SurfaceContainerHighDark = Color(0xFF252B26)
val SurfaceContainerHighestDark = Color(0xFF303631)
val InverseSurfaceDark = Color(0xFFDFE4DC)
val InverseOnSurfaceDark = Color(0xFF2C322D)
